package com.cadmium.redstone.ai;

import net.minecraft.core.BlockPos;

/**
 * An optimization suggestion generated by the AI controller.
 */
public class OptimizationSuggestion {
    private final OptimizationType type;
    private final BlockPos position;
    private final String description;
    private double priority;
    
    public OptimizationSuggestion(OptimizationType type, BlockPos position, String description) {
        this.type = type;
        this.position = position;
        this.description = description;
        this.priority = calculatePriority();
    }
    
    private double calculatePriority() {
        // Higher priority for suggestions that improve performance more
        return switch (type) {
            case ADD_REPEATER -> 3.0;
            case REMOVE_REDUNDANT_WIRE -> 2.0;
            case REROUTE_SIGNAL -> 4.0;
            case CONSOLIDATE_GATES -> 3.5;
        };
    }
    
    public OptimizationType getType() {
        return type;
    }
    
    public BlockPos getPosition() {
        return position;
    }
    
    public String getDescription() {
        return description;
    }
    
    public double getPriority() {
        return priority;
    }
    
    @Override
    public String toString() {
        return String.format("OptimizationSuggestion{type=%s, pos=%s, priority=%.1f, desc='%s'}",
            type, position, priority, description);
    }
    
    /**
     * Types of optimizations that can be suggested.
     */
    public enum OptimizationType {
        ADD_REPEATER,
        REMOVE_REDUNDANT_WIRE,
        REROUTE_SIGNAL,
        CONSOLIDATE_GATES
    }
}

